(defalias 'eb 'eval-buffer)
(defalias 'er 'eval-region)
(defalias 'ib 'ibuffer)
(defalias 'at 'ansi-term)
(defalias 'tl 'toggle-truncate-lines)
(defalias 'lm 'linum-mode)
(defalias 'wm 'whitespace-mode)
(defalias 'ag 'counsel-ag)
