

* Interaction
  Don't ask `yes/no?', ask `y/n?'

  #+BEGIN_SRC emacs-lisp
    (fset 'yes-or-no-p 'y-or-n-p)
  #+END_SRC

  get rid of bell

  #+BEGIN_SRC emacs-lisp
    (setq visible-bell t)
    (setq ring-bell-function 'ignore)
  #+END_SRC

* Automation
  - Make it to where when git or something else edits the file that
  it updates the buffer.

  #+BEGIN_SRC emacs-lisp
    (global-auto-revert-mode t)
  #+END_SRC

  - Don't present the usual startup message,
  and clear the scratch buffer.

  #+BEGIN_SRC emacs-lisp
    (setq require-final-newline t)
  #+END_SRC

  - save when I switch window

  #+BEGIN_SRC emacs-lisp
    (add-hook 'focus-out-hook (lambda () (save-some-buffers t)))
    (auto-save-visited-mode 0)
    (auto-save-mode 0)
  #+END_SRC

  - save all backups in one directory

  #+BEGIN_SRC emacs-lisp
    (setq backup-directory-alist `(("." . "~/.emacs-saves")))
  #+END_SRC

  I don't care Ill just use git and commit often :)

  #+BEGIN_SRC emacs-lisp
  (setq create-lockfiles nil)
  #+END_SRC

  * when we highlight a region and begin typing we delete
    the region

  #+BEGIN_SRC emacs-lisp
  (pending-delete-mode 1)
  #+END_SRC

  * get rid of menu bar

  #+BEGIN_SRC emacs-lisp
  (menu-bar-mode -1)
  #+END_SRC

  #+BEGIN_SRC emacs-lisp
    (defun comment-or-uncomment-region-or-line ()
    "Comments or uncomments the region or the current line if there's no active region." (interactive)
    (let (beg end)
    (if (region-active-p)
    (setq beg (region-beginning) end (region-end))
    (setq beg (line-beginning-position) end (line-end-position)))
    (comment-or-uncomment-region beg end)))
  #+END_SRC

  This makes it to where I dont have to type zsh every time I Ansi Term

  #+BEGIN_SRC emacs-lisp
    (setq explicit-shell-file-name "/bin/zsh")
  #+END_SRC

*** keybindings
    #+BEGIN_SRC emacs-lisp
      (global-set-key (kbd "s-<right>") 'move-end-of-line)
      (global-set-key (kbd "s-<left>") 'move-beginning-of-line)

      ;; backspace mac style
      (global-set-key (kbd "s-<backspace>") '(lambda () (interactive) (kill-line 0)) )

      (global-set-key (kbd "C-S-a") 'org-agenda)
      (global-set-key (kbd "s-p") 'projectile-find-file)
    #+END_SRC


* Formatting
  - Highlight Parens

  #+BEGIN_SRC emacs-lisp
    (show-paren-mode t)
  #+END_SRC

  Setting the region color has to happen AFTER the theme

  #+BEGIN_SRC emacs-lisp
    (set-face-attribute 'region nil :background "#C325D1")
  #+END_SRC

  - highlight my current line

  #+BEGIN_SRC emacs-lisp
    (global-hl-line-mode t)
  #+END_SRC

  - not for every language

  #+BEGIN_SRC emacs-lisp
    (setq default-tab-width 2)
  #+END_SRC

* UI
  - Don't need any of this stuff

  #+BEGIN_SRC emacs-lisp
    (menu-bar-mode nil)
    (scroll-bar-mode nil)
    (tool-bar-mode 0)
  #+END_SRC

  #+BEGIN_SRC emacs-lisp
    (setq-default cursor-type 'box)
  #+END_SRC

  - transparency function with a default of 90

  #+BEGIN_SRC emacs-lisp
    (defun transparency (value)
      "Sets the transparency of the frame window. 0=transparent/100=opaque."
      (interactive "nTransparency Value 0 - 100 opaque:")
      (set-frame-parameter (selected-frame) 'alpha value))

    (transparency 90)
  #+END_SRC

* Misc
  - Contact info.
  #+BEGIN_SRC emacs-lisp
    (setq user-full-name "Matthew Hecker"
      user-mail-address "matthecker@pm.me")
  #+END_SRC

  - Inhibit the dumb startup screen and message

  #+BEGIN_SRC emacs-lisp
    (setq inhibit-startup-message t)
    (setq initial-scratch-message nil)
  #+END_SRC

  - When opening a file, always follow symlinks.

  #+BEGIN_SRC emacs-lisp
    (setq vc-follow-symlinks t)
  #+END_SRC

  - default directory when opening emacs and saing files

  #+BEGIN_SRC emacs-lisp
    (setq default-directory "~/")
  #+END_SRC

  - set keys for Apple keyboard, for emacs in OS X

  #+BEGIN_SRC emacs-lisp
    (setq mac-command-modifier 'super) ; make cmd key do Meta
    ;; (setq mac-option-modifier 'super) ; make opt key do Super
  #+END_SRC

  - unbinding annoying keybinds that I sometimes fatfinger

  #+BEGIN_SRC emacs-lisp
    (global-unset-key (kbd "M-c"))
  #+END_SRC

  - loading elisp files always preffer a newer version?

  #+BEGIN_SRC emacs-lisp
    (setq load-prefer-newer t)
  #+END_SRC

  This sets region to bright pink!

  #+BEGIN_SRC emacs-lisp
    (set-face-attribute 'region nil :background "#C325D1")
  #+END_SRC

  set the default shell to zsh
  #+BEGIN_SRC emacs-lisp
    (setenv "SHELL" "/bin/zsh")
  #+END_SRC

  command t no longer annoyingly brings up font selection
  #+BEGIN_SRC emacs-lisp
    (global-set-key (kbd "s-t") nil)
  #+END_SRC
