#!/bin/zsh

set previewer pistol
set ratios 1:2:1

set hidden
set dircounts
set incsearch
set mouse
set icons
set shell zsh

map L playfolder
map D delete

# cmds/functions
cmd open ${{
    case $(file --mime-type "$f" -b) in
  image/vnd.djvu|application/pdf|application/octet-stream) setsid -f zathura "$fx" >/dev/null 2>&1 ;;
        text/*) $EDITOR "$fx";;
  image/x-xcf) setsid -f gimp "$f" >/dev/null 2>&1 ;;
  image/svg+xml) display -- "$f" ;;
  image/*) rotdir "$f" | grep -i "\.\(png\|jpg\|jpeg\|gif\|webp\|tif\|ico\)\(_large\)*$" | sxiv -aio 2>/dev/null | lf-select ;;
  audio/*) play "$f" ;;
  video/*) play "$f" ;;
  application/pdf|application/vnd*|application/epub*) setsid -f zathura "$f" >/dev/null 2>&1 ;;
        *) for f in "$fx"; do setsid -f $OPENER "$f" >/dev/null 2>&1; done;;
    esac
}}


map A rename # at the very end
map <enter> shell


cmd playfolder ${{
  IFS=$'\n' local lines=($(echo $fs))
  playlist=""

  for i in $lines
  do
    playlist+="\"${i}\" "
    enq $i
  done

  #play $playlist
}}


cmd setbg "$1"

cmd zoxide_dir ${{
   res="$(zoxide query -l | grep -iv cache | fzf 2>/dev/tty | sed 's/\\/\\\\/g;s/"/\\"/g')"
   if [ -d "$res" ]; then
      cmd="cd"
   else
      cmd="select"
   fi
 lf -remote "send $id $cmd \"$res\""
 }}

map go :zoxide_dir
