;;; Automatically generated by ‘recentf’ on Mon Nov 12 15:54:33 2018.

(setq recentf-list
      '(
	"/Users/matthew.hecker/code/dotfiles/.emacs.d/settings/package-settings.org"
	"/Users/matthew.hecker/code/dotfiles/.emacs.d/settings/keybindings.el"
	"/Users/matthew.hecker/.emacs.d/elpa/god-mode-20180117.1134/god-mode-autoloads.el"
	"/Users/matthew.hecker/code/dotfiles/.emacs.d/settings/basic.org"
	))

(setq recentf-filter-changer-current 'nil)


;; Local Variables:
;; coding: utf-8-emacs
;; End:
