#! /bin/sh


gap=15

bspc monitor -d 1 2 3 '4' 5 6 7

horizontal=$(xrandr | grep \* | awk '{print $1}' | cut -d "x" -f 1)
percentage="0.01"
horizontal_padding=$(echo "($horizontal * $percentage) - 13" | bc -l)
echo $horizontal_padding
echo $horizontal

bspc config border_width         1.5
bspc config window_gap          18

bspc config window_gap $gap;
bspc config top_padding 40
bspc config left_padding $horizontal_padding
bspc config right_padding $horizontal_padding
bspc config bottom_padding 15

bspc config focused_border_color "#68a6c4"
bspc config normal_border_color "#484848"
  
bspc config focus_follows_pointer true

bspc rule -a google-chrome desktop='^2' follow=off
bspc rule -a Google-chrome desktop='^2' follow=off

bspc rule -a brave-browser desktop='^3' follow=off
bspc rule -a Brave-browser desktop='^3' follow=off
bspc rule -a Slack desktop='^4' follow=off
