#!/usr/bin/env expect


spawn -noecho ~/.config/google-cloud-sdk/install.sh
expect "Installation directory (this will create a google-cloud-sdk subdirectory) (/home/hoffs):" { send -- "~/.config/google-cloud-sdk/\n" }
expect "Remove it before installing? (y/N):" { send -- "y\n" }
expect "Do you want to help improve the Google Cloud SDK (y/N)?" { send -- "N\n" }
expect "*?*" { send -- "Y\n" }
expect "*:*" { send -- "\n" }
interact
